M48
; DRILL file {KiCad 9.0.0} date 2026-01-16T11:46:07+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-16T11:46:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.397
%
G90
G05
T1
X198.272Y-119.786
X198.272Y-127.786
T2
X172.039Y-61.722
X182.042Y-61.722
M30
